Repository ssg-240304-java2/test4, pull requests merged in 2024-04, with the labels that each got.

#2 Good Bam
  Dong.md
Labels: bug

#3 파일업로드
  hyeongyun.md
Labels: good first issue

#1 준영 파일 업로드
  JUNYOUNG.md
Labels: documentation
